language: c
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install check subunit lcov
  - pip install --user --upgrade pip
  - pip install --user cpp-coveralls

script:
  - make
  - ./test_radit

after_success:
  - coveralls --include radit.c --include radit.h --gcov-options '\-lp'
